### ISSUE TITLE
How to install on macOS?

### ISSUE THREAD

**Issue by ghost** [nspo/pyvisualcompare#1]
Please update install instructions. Possibly add instructions for those not using `apt` but python for the install, i.e.

`$ python3 -m pip install  <package>`

Had issue finding `python3-pyqt5` will PyQt5 (5.15.0) work with your application?

Had issues finding `xvfb` will pyxvfb (0.0.2) work with your application?
```
$ pip search xvfb
robotframework-xvfb (1.2.2)  - Robot library for interacting with Xvfb
pytest-xvfb (2.0.0)          - A pytest plugin to run Xvfb for tests.
nose-xvfb (0.13.1)           - Virtual display nose plugin through Xvfb
pyxvfb (0.0.2)               - Python wrapper for the xvfb command
PyVirtualDisplay (1.3.2)     - python wrapper for Xvfb, Xephyr and Xvnc
headless-pdfkit (0.1.5)      - A headless version of pdfkit which makes use of xvfb-run
xvfbwrapper (0.2.9)          - run headless display inside X virtual framebuffer (Xvfb)
xvfbman (1.0.0)              - A python module for managing Xvfb sessions / ensuring DISPLAY through a simple interface
```

```
$ pip search python3-pyqt5
PyQt5-sip (12.8.1)                      - The sip module support for PyQt5
PyQt5-stubs (5.14.2.2)                  - PEP561 stub files for the PyQt5 framework
pyqt5-tools (5.15.0.1.7.1)              - Tools to supplement the official PyQt5 wheels
pyqt5-notificator (1.0.12)              - pyqt5_notificator is a module to generate pyqt5 desktop
                                          notifications
PyQt5 (5.15.0)                          - Python bindings for the Qt cross platform application
                                          toolkit

```

**Comment by nspo** [comment]
Thanks for the request. Not all needed applications are installable with `pip` though (e.g. `xvfb` is not a Python application). What platform are you trying to run on?

**Comment by ghost** [comment]
I am trying to install and run on macOS. Not sure why I presumed those were to be installed with Python...

EDIT
I use Homebrew as my package manager.

**Comment by nspo** [comment]
Docker (#2) might be a viable solution for most parts but AFAIK MacOS does not have an X server anymore, which will probably complicate things.

**Comment by nspo** [comment]
@jprokos Feel free to try out the Docker version: https://github.com/nspo/pyvisualcompare/issues/2#issuecomment-688498122

If you try it, please also report whether it works! Thanks.

**Comment by nspo** [comment]
Closing this as a possible solution was added to the README and no feedback was received.
