### ISSUE TITLE
Request: Prepare docker image on docker.hub

### ISSUE THREAD

**Issue by dhlavaty** [nspo/pyvisualcompare#2]
It would be really nice, to be able to run `pyvisualcompare` in docker (downloading from docker.hub)

**Comment by nspo** [comment]
Yes, good idea. Depending on the host system it might be a bit problematic due to the GUI - e.g. for systems without an X server. I'll have to try that out. What are you trying to run it on?

**Comment by dhlavaty** [comment]
Mac

**Comment by nspo** [comment]
Just to check, do you intend to run the frontend on MacOS or the backend (with `urlwatch`)?

**Comment by dhlavaty** [comment]
backend of course

**Comment by nspo** [comment]
I added a test image as `nspohrer/pyvisualcompare`, you're welcome to try it out. 

Try something like the following (obviously you can change the URL and other parameters):

`docker run -it -u qtuser nspohrer/pyvisualcompare /app/pyvisualcompare-md5.sh --crop-x 8 --crop-y 5 --crop-w 232 --crop-h 58 heise.de`

For other people trying to run the frontend:

Under Linux (with X11), the following works for me to run the GUI:

`docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -u qtuser nspohrer/pyvisualcompare python3 /app/main.py`

Under MacOS you probably need to install XQuartz and play around a bit with the parameters, see e.g. [here](https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285).

**Comment by nspo** [comment]
Closed as it's added to the README and no error was reported back
