### ISSUE TITLE
add delay

### ISSUE THREAD

**Issue by disgustipated** [nspo/pyvisualcompare#3]
Is there a way to have a slight delay before the snapshot of the page is taken? I have a page I'm trying to setup with this that has a couple images that dont load until about a half a second after the page completely loads.

**Comment by nspo** [comment]
Yes, there is!

Try to add something like `--javascript-delay 1000` (for a 1000 ms delay) in the call to `pyvisualcompare-md5.sh`. 

Full example: `pyvisualcompare-md5.sh --crop-x 8 --crop-y 5 --crop-w 232 --crop-h 58 --javascript-delay 1000 heise.de`

I'll add this to the README.

**Comment by disgustipated** [comment]
Awesome, I'll try that, thank you much!

**Comment by disgustipated** [comment]
Worked perfectly.
For anyone else doing this, I had to add it on the front end when I ran main.py
`python3 main.py --javascript-delay 4000`
and then also used it in the urlwatch edit rule like in the example above

**Comment by nspo** [comment]
@disgustipated I don't think parameters passed to `main.py` had an effect actually! But I added an option to the GUI so that the delay can be configured there - this delay will then be used while running the frontend and it will also be included in the generated backend command.

**Comment by disgustipated** [comment]
Oh cool, thanks!
