### ISSUE TITLE
question

### ISSUE THREAD

**Issue by marz-hunter** [nspo/pyvisualcompare#5]
how to install this on ubuntu 18 vps, does it need two vps?. is there a video tutorial to install this on vps?. thank you

**Comment by marz-hunter** [comment]
if there is a video documentation for urlwatch and also this tool it, will really help a beginner like me, thanks

**Comment by nspo** [comment]
You don't need two servers, you only need a single one. Regarding server setup, maybe it would make sense to first try out `urlwatch` ([documentation](https://urlwatch.readthedocs.io/en/latest/)) without `pyisualcompare` to get a better understanding of it. When that works, adding a `pyvisualcompare` command will be easy.

You do need a system to run the frontend GUI once though, preferably with Linux as that should be the easiest way. Maybe install Ubuntu in a Virtual Machine (e.g. with VirtualBox) or boot from a Ubuntu Live USB drive to try out the section _Frontend (GUI) on Linux_ of the README.

I understand that a video tutorial would be nice but using `pyisualcompare` is based on using several different other software components which may change independently (especially `urlwatch` or the OS it runs on). Therefore it may be necessary to figure out the steps with the help of the README. Hope this helps.

**Comment by marz-hunter** [comment]
so
1. I need a VPS server for urlwatch
2. On the second server I need to install xrdp for the GUI?
thank you for your answer

**Comment by nspo** [comment]
1. Yes, that is correct.
2. No, you do not need a second server. Before setting up pyvisualcompare/urlwatch you need to run the frontend application **once** (to get the command which is later run on the backend server). You can do this on your personal computer (not a server) or in many other ways. If you use Windows or MacOS, it may make sense to install pyvisualcompare on the server, then do something like [in this tutorial](https://kb.iu.edu/d/bdnt) and start the pyvisualcompare frontend on the remote server but show the GUI locally (through graphics forwarding). Alternatively, you can try to use docker to run the frontend locally or use a Virtual Machine (VM, e.g. with VirtualBox). If you use a VM, start Ubuntu in the VM and then just follow the normal non-docker guide in the README (install requirements, download pyvisualcompare, start pyvisualcompare frontend with `python3 main.py`).

**Comment by marz-hunter** [comment]
I managed to do it, create a vps and install xrdp then install all via xrdp. but how to enter multiple domains at once?

and for slack notifications
--- Mon, 21 Sep 2020 02:20:03 +0000
+++ Mon, 21 Sep 2020 02:30:03 +0000
@@ -1 +1 @@
-4682191ddfdcf92b2f746465c5a7ab8b -
+ 0d619ed20049725c280c06011032809d -

can't we see the previous picture to compare?

**Comment by nspo** [comment]
You can add multiple domains with multiple `urlwatch` commands. Just generate a new one and add it to the `urlwatch` config.

Sadly before/after pictures are not saved or shown because only a hash is computed. That would also need a much tighter integration with urlwatch than at the moment.

**Comment by marz-hunter** [comment]
So at this time we can not compare changes to the page?, or there is another way I do not understand how to compare.

**Comment by nspo** [comment]
You select a specific area of a web page on the pyvisualcompare frontend. You get notified automatically when that specific area changes (because then the hash of a screenshot of that area changes) via Slack/Telegram/Whatever. You don't automatically get an image comparison in your notification, you have to look manually at the web page to see what the current state is.
